version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_gastos
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: gastos_db
    ports:
      - "5433:5432"
    volumes:
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - dbdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_gastos
    restart: always
    environment:
      env_file: backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  dbdata:
